// data.js — Full worldwide PC parts inventory
// Each part: { id, cat, brand, name, specs, price, stock: 'in'|'low'|'out', limited: bool, preorder: bool }

const PARTS = [
  // ===== CPUs =====
  { id:'c1', cat:'cpu',  brand:'AMD',     name:'Ryzen 5 7600',              specs:'6C/12T · 5.1GHz boost · 65W TDP',        price:199,  stock:'in' },
  { id:'c2', cat:'cpu',  brand:'AMD',     name:'Ryzen 7 7800X3D',          specs:'8C/16T · 5.05GHz boost · 3D V-Cache',   price:419,  stock:'in' },
  { id:'c3', cat:'cpu',  brand:'AMD',     name:'Ryzen 9 9950X',            specs:'16C/32T · 5.7GHz boost · 170W TDP',    price:649,  stock:'in' },
  { id:'c4', cat:'cpu',  brand:'Intel',   name:'Core i5-13600K',           specs:'14C/20T · 5.1GHz boost · 125W TDP',    price:289,  stock:'in' },
  { id:'c5', cat:'cpu',  brand:'Intel',   name:'Core i7-14700K',           specs:'20C/28T · 5.6GHz boost · 253W TDP',    price:439,  stock:'low' },
  { id:'c6', cat:'cpu',  brand:'Intel',   name:'Core i9-14900K',           specs:'24C/32T · 6.0GHz boost · 320W TDP',    price:619,  stock:'low' },
  { id:'c7', cat:'cpu',  brand:'Intel',   name:'Core Ultra 9 285K',       specs:'24C/24T · Arrow Lake · 6.0GHz',        price:699,  stock:'in' },
  { id:'c8', cat:'cpu',  brand:'AMD',     name:'Threadripper 7995WX',     specs:'96C/192T · 5.7GHz · HEDT beast',       price:10999,stock:'low', limited:true },
  { id:'c9', cat:'cpu',  brand:'IBM',     name:'POWER9 8336 4-socket',    specs:'HPC server · 450W · rare spare',        price:4500, stock:'out', limited:true, preorder:true },
  { id:'c10',cat:'cpu',  brand:'AMD',     name:'Ryzen 5 9600X',           specs:'6C/12T · Zen 5 · 5.4GHz boost · 65W',   price:249,  stock:'in' },
  { id:'c11',cat:'cpu',  brand:'Intel',   name:'Core Ultra 7 265K',       specs:'20C/20T · Arrow Lake · 5.5GHz',         price:399,  stock:'in' },
  { id:'c12',cat:'cpu',  brand:'AMD',     name:'Ryzen 7 9700X',            specs:'8C/16T · Zen 5 · 5.5GHz boost · 65W',    price:359,  stock:'in' },
  { id:'c13',cat:'cpu',  brand:'Intel',   name:'Core Ultra 5 245K',       specs:'14C/14T · Arrow Lake · 5.2GHz',          price:319,  stock:'in' },
  { id:'c14',cat:'cpu',  brand:'AMD',     name:'Ryzen 7 7700',             specs:'8C/16T · Zen 4 · 5.3GHz boost · 65W',    price:279,  stock:'low' },
  { id:'c15',cat:'cpu',  brand:'AMD',     name:'Ryzen 5 7500F',             specs:'6C/12T · Zen 4 · 5.0GHz boost · 65W',    price:179,  stock:'in' },
  { id:'c16',cat:'cpu',  brand:'Intel',   name:'Core i5-14600KF',          specs:'14C/20T · 5.3GHz boost · 181W',           price:259,  stock:'in' },
  { id:'c17',cat:'cpu',  brand:'Intel',   name:'Xeon w7-2495X',             specs:'24C/48T · workstation · 225W TDP',        price:1399, stock:'low', limited:true },

  // ===== GPUs =====
  { id:'g1', cat:'gpu',  brand:'NVIDIA',  name:'RTX 4060',                specs:'8GB GDDR6 · 120W · 4096 shaders',        price:299,  stock:'in' },
  { id:'g2', cat:'gpu',  brand:'NVIDIA',  name:'RTX 4070 Ti Super',       specs:'16GB GDDR6X · 285W · 7168 shaders',     price:749,  stock:'in' },
  { id:'g3', cat:'gpu',  brand:'NVIDIA',  name:'RTX 4080 Super',          specs:'16GB GDDR6X · 320W · 7680 shaders',     price:999,  stock:'in' },
  { id:'g4', cat:'gpu',  brand:'NVIDIA',  name:'RTX 4090',                specs:'24GB GDDR6X · 450W · 16384 shaders',    price:1599, stock:'low', limited:true },
  { id:'g5', cat:'gpu',  brand:'AMD',     name:'Radeon RX 7800 XT',       specs:'16GB GDDR6 · 263W · 3840 shaders',      price:499,  stock:'in' },
  { id:'g6', cat:'gpu',  brand:'AMD',     name:'Radeon RX 7900 XTX',      specs:'24GB GDDR6 · 355W · 6144 shaders',      price:899,  stock:'in' },
  { id:'g7', cat:'gpu',  brand:'AMD',     name:'Radeon RX 9000 XT',       specs:'Next-gen RDNA4 · rumored 32GB',         price:999,  stock:'preorder', preorder:true, limited:true },
  { id:'g8', cat:'gpu',  brand:'NVIDIA',  name:'RTX 6000 Ada',            specs:'48GB GDDR6 · workstation · 300W',       price:6800, stock:'in', limited:true },
  { id:'g9', cat:'gpu',  brand:'ASUS',    name:'ROG Strix RTX 4090 Titanium',specs:'840W · 24GB · premium build',        price:1999, stock:'low', limited:true },
  { id:'g10',cat:'gpu',  brand:'NVIDIA',  name:'RTX 5070',                specs:'12GB GDDR7 · DLSS 4 · 250W',             price:549,  stock:'in' },
  { id:'g11',cat:'gpu',  brand:'AMD',     name:'Radeon RX 9070 XT',       specs:'16GB GDDR6 · RDNA 4 · 304W',            price:599,  stock:'low' },
  { id:'g12',cat:'gpu',  brand:'NVIDIA',  name:'RTX 5060 Ti',              specs:'16GB GDDR7 · DLSS 4 · 180W',              price:429,  stock:'in' },
  { id:'g13',cat:'gpu',  brand:'AMD',     name:'Radeon RX 9060 XT',       specs:'16GB GDDR6 · RDNA 4 · 160W',             price:399,  stock:'in' },
  { id:'g14',cat:'gpu',  brand:'Intel',   name:'Arc B580 Limited Edition', specs:'12GB GDDR6 · Xe2 · AV1 encode',          price:249,  stock:'in', limited:true },
  { id:'g15',cat:'gpu',  brand:'NVIDIA',  name:'RTX 5090 Founders Edition',specs:'32GB GDDR7 · DLSS 4 · 575W',              price:1999, stock:'low', limited:true },
  { id:'g16',cat:'gpu',  brand:'AMD',     name:'Radeon RX 7900 GRE',       specs:'16GB GDDR6 · RDNA 3 · 260W',              price:529,  stock:'in' },
  { id:'g17',cat:'gpu',  brand:'Intel',   name:'Arc A770 16GB',             specs:'16GB GDDR6 · Xe HPG · AV1 encode',        price:299,  stock:'low' },

  // ===== RAM =====
  { id:'r1', cat:'ram',  brand:'G.Skill',  name:'FlareX DDR5-6000 32GB (2x16)', specs:'CL30 · 1.35V · AM5 optimized',    price:119,  stock:'in' },
  { id:'r2', cat:'ram',  brand:'Corsair',  name:'Vengeance DDR5-6400 32GB (2x16)',specs:'CL32 · Intel XMP3.0',            price:134,  stock:'in' },
  { id:'r3', cat:'ram',  brand:'G.Skill',  name:'Trident Z5 DDR5-8000 64GB (2x32)',specs:'CL36 · extreme OC',           price:339,  stock:'low', limited:true },
  { id:'r4', cat:'ram',  brand:'Samsung',  name:'JC500 FBDIMM 256GB',        specs:'server ECC · rare find',            price:1450, stock:'out', limited:true, preorder:true },
  { id:'r5', cat:'ram',  brand:'Kingston', name:'Fury Renegade DDR5-8400 128GB',specs:'4x32GB · overclocking beast', price:580,  stock:'low', limited:true },
  { id:'r6', cat:'ram',  brand:'Corsair',  name:'Vengeance DDR5-6000 64GB (2x32)',specs:'CL36 · AMD EXPO · low profile', price:219, stock:'in' },
  { id:'r7', cat:'ram',  brand:'Kingston', name:'Fury Beast DDR4-3200 32GB (2x16)',specs:'CL16 · Intel XMP · value kit', price:69, stock:'in' },
  { id:'r8', cat:'ram',  brand:'TeamGroup',name:'T-Force Delta RGB DDR5-6000 32GB',specs:'CL30 · EXPO/XMP · RGB heatsink', price:109, stock:'in' },
  { id:'r9', cat:'ram',  brand:'Corsair',  name:'Dominator Titanium DDR5-7200 48GB',specs:'2x24GB · CL36 · premium kit', price:229, stock:'low', limited:true },
  { id:'r10',cat:'ram',  brand:'Crucial',  name:'Pro DDR5-5600 32GB (2x16)', specs:'CL46 · 1.1V · simple heatsink',         price:79,  stock:'in' },
  { id:'r11',cat:'ram',  brand:'G.Skill',  name:'Ripjaws S5 DDR5-5600 96GB', specs:'2x48GB · CL40 · compact heatsinks',      price:249, stock:'in' },
  { id:'r12',cat:'ram',  brand:'Patriot',  name:'Viper Steel DDR4-3600 32GB', specs:'2x16GB · CL18 · XMP 2.0',               price:74,  stock:'in' },
  { id:'r13',cat:'ram',  brand:'TeamGroup',name:'T-Create Expert DDR5-6400 96GB',specs:'2x48GB · CL34 · creator kit',          price:299, stock:'low' },

  // ===== Motherboards =====
  { id:'m1', cat:'mobo',  brand:'ASUS',   name:'ROG Strix B650-E',        specs:'AM5 · DDR5 · PCIe 5.0 · WiFi 6E',       price:279,  stock:'in' },
  { id:'m2', cat:'mobo',  brand:'MSI',    name:'MAG Z790 Tomahawk WiFi',  specs:'LGA1700 · DDR5 · PCIe 5.0 · 16+1 phases',price:249,  stock:'in' },
  { id:'m3', cat:'mobo',  brand:'ASUS',   name:'ROG Crosshair X670E Hero',specs:'AM5 · DDR5 · PCIe 5.0 x2 · 2.5G LAN',  price:549,  stock:'in' },
  { id:'m4', cat:'mobo',  brand:'Gigabyte',name:'Z890 AORUS Master',      specs:'LGA1851 · DDR5 · 20+1 phases · Wi-Fi 7',price:599,  stock:'in', limited:true },
  { id:'m5', cat:'mobo',  brand:'ASRock', name:'TRX50 Phantom Gaming',    specs:'TRX50 · threadripper · 8-channel DDR5', price:999,  stock:'low', limited:true },
  { id:'m6', cat:'mobo',  brand:'MSI',    name:'B650 Gaming Plus WiFi',   specs:'AM5 · DDR5 · PCIe 4.0 · WiFi 6E',       price:159,  stock:'in' },
  { id:'m7', cat:'mobo',  brand:'ASUS',   name:'TUF Gaming Z790-Plus',    specs:'LGA1700 · DDR5 · PCIe 5.0 · WiFi 6',    price:219,  stock:'low' },
  { id:'m8', cat:'mobo',  brand:'Gigabyte',name:'B650 Eagle AX',           specs:'AM5 · DDR5 · PCIe 5.0 · WiFi 6E',       price:179,  stock:'in' },
  { id:'m9', cat:'mobo',  brand:'ASRock', name:'B850 Steel Legend WiFi',   specs:'AM5 · DDR5 · PCIe 5.0 · WiFi 7',        price:249,  stock:'in' },
  { id:'m10',cat:'mobo',  brand:'MSI',    name:'PRO B760-P WiFi DDR5',     specs:'LGA1700 · DDR5 · PCIe 4.0 · WiFi 6E',   price:169,  stock:'in' },
  { id:'m11',cat:'mobo',  brand:'ASUS',   name:'ROG Strix X870-F Gaming',  specs:'AM5 · DDR5 · PCIe 5.0 · WiFi 7',        price:329,  stock:'in' },
  { id:'m12',cat:'mobo',  brand:'Gigabyte',name:'Z790 AORUS Elite AX',      specs:'LGA1700 · DDR5 · PCIe 5.0 · WiFi 6E',   price:229,  stock:'in' },
  { id:'m13',cat:'mobo',  brand:'ASRock', name:'B650M Pro RS WiFi',         specs:'AM5 · DDR5 · M-ATX · WiFi 6E',            price:139,  stock:'in' },

  // ===== Storage =====
  { id:'s1', cat:'storage', brand:'Samsung',  name:'990 Pro 2TB NVMe',     specs:'ZNS · 7400MB/s read · PCIe 4.0',         price:159,  stock:'in' },
  { id:'s2', cat:'storage', brand:'WD',       name:'SN850X 2TB NVMe',     specs:'7300MB/s · Gen4 · gaming optimized',      price:154,  stock:'in' },
  { id:'s3', cat:'storage', brand:'SK hynix', name:'Platinum P41 4TB',     specs:'7000MB/s · Gen4 · incredible endurance', price:299,  stock:'low' },
  { id:'s4', cat:'storage', brand:'Samsung',  name:'PM1000 PRO 30.72TB U.2',specs:'Enterprise NVMe · 200k IOPS',          price:3400, stock:'in', limited:true },
  { id:'s5', cat:'storage', brand:'Seagate',  name:'Exos X24 24TB HDD',   specs:'Enterprise · CMR · 7200 RPM · 256MB cache',price:429, stock:'in' },
  { id:'s6', cat:'storage', brand:'Apple',    name:'Mac Studio SSD 8TB',   specs:'Proprietary blade · rare upgrade',         price:1699, stock:'out', limited:true, preorder:true },
  { id:'s7', cat:'storage', brand:'Crucial',  name:'T500 2TB NVMe',        specs:'7400MB/s · Gen4 · direct-storage ready',   price:144,  stock:'in' },
  { id:'s8', cat:'storage', brand:'WD',       name:'Red Pro 12TB HDD',     specs:'NAS · CMR · 7200 RPM · 512MB cache',      price:299,  stock:'in' },
  { id:'s9', cat:'storage', brand:'Samsung',  name:'990 EVO Plus 2TB NVMe', specs:'7250MB/s · Gen4/5 · intelligent TurboWrite',price:169, stock:'in' },
  { id:'s10',cat:'storage', brand:'Solidigm', name:'P44 Pro 2TB NVMe',      specs:'7000MB/s · Gen4 · high endurance',        price:139,  stock:'in' },
  { id:'s11',cat:'storage', brand:'Toshiba',  name:'N300 8TB HDD',          specs:'NAS · CMR · 7200 RPM · 256MB cache',      price:189,  stock:'low' },
  { id:'s12',cat:'storage', brand:'Kingston', name:'KC3000 1TB NVMe',        specs:'7000MB/s · Gen4 · TLC NAND',              price:89,   stock:'in' },
  { id:'s13',cat:'storage', brand:'Lexar',    name:'NM790 4TB NVMe',         specs:'7400MB/s · Gen4 · gaming storage',        price:289,  stock:'in' },
  { id:'s14',cat:'storage', brand:'Seagate',  name:'IronWolf Pro 16TB HDD',  specs:'NAS · CMR · 7200 RPM · 256MB cache',      price:389,  stock:'low' },

  // ===== PSUs =====
  { id:'p1', cat:'psu',  brand:'Corsair',  name:'RM850x Shift',          specs:'850W · 80+ Gold · fully modular · ATX3.0',  price:149,  stock:'in' },
  { id:'p2', cat:'psu',  brand:'Seasonic', name:'Focus GX-1000',         specs:'1000W · 80+ Gold · fanless mode',          price:179,  stock:'in' },
  { id:'p3', cat:'psu',  brand:'be quiet!',name:'Straight Power 12 1200W',specs:'1200W · 80+ Gold · silent fan',           price:299,  stock:'in' },
  { id:'p4', cat:'psu',  brand:'Thermaltake',name:'Toughpower Grand RGB 1600W',specs:'1600W · 80+ Platinum · OLED screen',price:379,  stock:'low', limited:true },
  { id:'p5', cat:'psu',  brand:'Seasonic', name:'Prime TX-3 2000W',     specs:'2000W · 80+ Titanium · 80A · beast',       price:649,  stock:'out', limited:true, preorder:true },
  { id:'p6', cat:'psu',  brand:'Super Flower',name:'Leadex VII Gold 850W', specs:'850W · 80+ Gold · ATX 3.1 · modular',     price:139,  stock:'in' },
  { id:'p7', cat:'psu',  brand:'be quiet!',name:'Pure Power 12 M 750W', specs:'750W · 80+ Gold · quiet modular design',   price:119,  stock:'in' },
  { id:'p8', cat:'psu',  brand:'MSI',      name:'MAG A850GL PCIE5',       specs:'850W · 80+ Gold · ATX 3.0 · modular',      price:119,  stock:'in' },
  { id:'p9', cat:'psu',  brand:'EVGA',     name:'SuperNOVA 1000 GT',      specs:'1000W · 80+ Gold · fully modular',         price:159,  stock:'low' },
  { id:'p10',cat:'psu',  brand:'FSP',      name:'Hydro PTM X PRO 1200W',  specs:'1200W · 80+ Platinum · ATX 3.0',          price:249,  stock:'in' },
  { id:'p11',cat:'psu',  brand:'Corsair',  name:'RM1000e ATX 3.1',        specs:'1000W · 80+ Gold · modular · 12V-2x6',    price:169,  stock:'in' },
  { id:'p12',cat:'psu',  brand:'Thermaltake',name:'Toughpower GF3 850W',   specs:'850W · 80+ Gold · PCIe 5.0 · modular',    price:129,  stock:'in' },
  { id:'p13',cat:'psu',  brand:'Seasonic', name:'Vertex GX-1200',          specs:'1200W · 80+ Gold · ATX 3.0 · modular',   price:239,  stock:'low' },

  // ===== Cases =====
  { id:'t1', cat:'case', brand:'Fractal',  name:'Design Ridge',          specs:'M-ATX · low profile · clean minimal',       price:79,   stock:'in' },
  { id:'t2', cat:'case', brand:'Corsair',  name:'5000D Airflow',        specs:'ATX · massive airflow · easy build',         price:99,   stock:'in' },
  { id:'t3', cat:'case', brand:'Lian Li',  name:'O11 Dynamic EVO',      specs:'ATX · iconic glass · RGB ecosystem',         price:169,  stock:'in' },
  { id:'t4', cat:'case', brand:'SFF Lab',  name:'H Yokohama',           specs:'Mini-ITX · premium aluminum · cable mgmt',   price:299,  stock:'low', limited:true },
  { id:'t5', cat:'case', brand:'Rosewill', name:'RNX-EXTREME 10',        specs:'Full-tower · 12x HDD · server style',        price:119,  stock:'in' },
  { id:'t6', cat:'case', brand:'NZXT',     name:'H7 Flow',               specs:'ATX · mesh front · clean cable routing',     price:129,  stock:'in' },
  { id:'t7', cat:'case', brand:'Cooler Master',name:'NR200P V2',          specs:'Mini-ITX · compact airflow · tempered glass',price:99,  stock:'in' },
  { id:'t8', cat:'case', brand:'Phanteks', name:'NV5 MKII',                specs:'ATX · panoramic glass · vertical GPU ready',price:139, stock:'in' },
  { id:'t9', cat:'case', brand:'be quiet!',name:'Pure Base 500DX',         specs:'ATX · mesh airflow · subtle ARGB',          price:99,  stock:'in' },
  { id:'t10',cat:'case', brand:'Jonsbo',   name:'D31 Mesh Screen',          specs:'M-ATX · compact · optional display',       price:109,  stock:'low' },
  { id:'t11',cat:'case', brand:'Lian Li',  name:'Lancool 216 RGB',          specs:'ATX · dual 160mm fans · high airflow',      price:119,  stock:'in' },
  { id:'t12',cat:'case', brand:'HYTE',     name:'Y70 Touch Infinite',       specs:'ATX · panoramic glass · 4K touchscreen',   price:359,  stock:'low', limited:true },
  { id:'t13',cat:'case', brand:'SilverStone',name:'SUGO 14',                specs:'Mini-ITX · compact cube · GPU support',    price:109,  stock:'in' },

  // ===== Cooling =====
  { id:'k1', cat:'cooling', brand:'Noctua',  name:'NH-D15 chromax.black', specs:'140mm · 22dB · dual tower · legendary',    price:109,  stock:'in' },
  { id:'k2', cat:'cooling', brand:'Arctic',  name:'Liquid Freezer III 360',specs:'360mm AIO · 6th gen pump · VR cool',    price:109,  stock:'in' },
  { id:'k3', cat:'cooling', brand:'Bitspower',name:'Watercool HE-360 ARGB',specs:'360mm · copper CP · white aesthetic',     price:229,  stock:'in', limited:true },
  { id:'k4', cat:'cooling', brand:'CoolerMaster', name:'MasterLiquid ML120R V2',specs:'120mm · 1800RPM · RGB · budget AIO',  price:59,   stock:'in' },
  { id:'k5', cat:'cooling', brand:'Laing',   name:'D5 NEXT pump + 5x 360mm rad',specs:'Custom loop essentials · rare bundle',price:2999, stock:'out', limited:true, preorder:true },
  { id:'k6', cat:'cooling', brand:'be quiet!',name:'Dark Rock Pro 5',       specs:'Dual tower · 270W TDP · low noise',        price:89,   stock:'in' },
  { id:'k7', cat:'cooling', brand:'DeepCool',name:'LS720 SE 360',           specs:'360mm AIO · ARGB · high static pressure',   price:99,   stock:'in' },
  { id:'k8', cat:'cooling', brand:'Thermalright',name:'Phantom Spirit 120 SE',specs:'Dual tower · 7 heatpipes · AM5/LGA1851',price:39, stock:'in' },
  { id:'k9', cat:'cooling', brand:'Arctic',  name:'Liquid Freezer III 240', specs:'240mm AIO · VRM fan · low noise',          price:89,  stock:'in' },
  { id:'k10',cat:'cooling', brand:'Lian Li', name:'Galahad II Trinity 360', specs:'360mm AIO · triple-chamber pump · ARGB',   price:159, stock:'low' },
  { id:'k11',cat:'cooling', brand:'ID-COOLING',name:'FROSTFLOW X 240',       specs:'240mm AIO · dual PWM fans · AM5 ready',    price:59,  stock:'in' },
  { id:'k12',cat:'cooling', brand:'Noctua',  name:'NH-U12A chromax.black',   specs:'120mm · dual fans · premium air cooling',   price:119, stock:'in' },
  { id:'k13',cat:'cooling', brand:'Corsair', name:'iCUE H150i Elite Capellix',specs:'360mm AIO · LCD-ready · RGB fans',        price:189, stock:'low' },
];

// Category display labels
const CAT_LABELS = {
  all:'All Parts',
  cpu:'CPUs',
  gpu:'GPUs',
  ram:'RAM',
  mobo:'Motherboards',
  storage:'Storage',
  psu:'PSUs',
  case:'Cases',
  cooling:'Cooling',
};
